SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_id=7;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id=1166578;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_id<3;
SELECT COUNT(*) FROM movie_info_idx mi_idx WHERE mi_idx.info_type_id=99;
SELECT COUNT(*) FROM title t WHERE t.kind_id<7 AND t.production_year>2014;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id>3435413 AND ci.role_id>1;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<2804597;
SELECT COUNT(*) FROM movie_info_idx mi_idx WHERE mi_idx.info_type_id=101;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<2973;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<40985;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>10064;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id>38651 AND mc.company_type_id<2;
SELECT COUNT(*) FROM movie_info_idx mi_idx WHERE mi_idx.info_type_id>99;
SELECT COUNT(*) FROM movie_info_idx mi_idx WHERE mi_idx.info_type_id>101;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<1861827;
SELECT COUNT(*) FROM movie_info_idx mi_idx WHERE mi_idx.info_type_id=100;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>2439;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id>2575755;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_id<8;
SELECT COUNT(*) FROM movie_info_idx mi_idx WHERE mi_idx.info_type_id>100;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<18009;
SELECT COUNT(*) FROM title t WHERE t.kind_id>1 AND t.production_year>1978;
SELECT COUNT(*) FROM movie_info_idx mi_idx WHERE mi_idx.info_type_id<100;
SELECT COUNT(*) FROM title t WHERE t.kind_id>1 AND t.production_year=2012;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=5166;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<3696 AND mc.company_type_id<2;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<957;
SELECT COUNT(*) FROM title t WHERE t.kind_id<4 AND t.production_year<2010;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<3063850;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<55405;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id>67;
SELECT COUNT(*) FROM title t WHERE t.kind_id<7 AND t.production_year=2010;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<130027 AND ci.role_id=1;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_id<7;
SELECT COUNT(*) FROM title t WHERE t.kind_id<4;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=17086;
SELECT COUNT(*) FROM title t WHERE t.kind_id<2;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<19242;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>4899;
SELECT COUNT(*) FROM title t WHERE t.kind_id=7;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=4952;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_id=8;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=115;
SELECT COUNT(*) FROM title t WHERE t.kind_id<7;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<3053817 AND ci.role_id=1;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_id>17;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id>100258;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_id>15;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<49236;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id>134983;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<6 AND mc.company_type_id=2;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=5661;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_id>1;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_id>94;
SELECT COUNT(*) FROM title t WHERE t.kind_id>1;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_id<17;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>2256;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_id<4;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_id>16;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<6 AND mc.company_type_id<2;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<14695;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>1905;
SELECT COUNT(*) FROM title t WHERE t.kind_id=1 AND t.production_year>2008;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<16264;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>7418;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id>3742;
SELECT COUNT(*) FROM movie_info_idx mi_idx WHERE mi_idx.info_type_id<101;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id=19 AND mc.company_type_id=1;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<2494196;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id>3577314 AND ci.role_id>2;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_id<2;
SELECT COUNT(*) FROM title t WHERE t.kind_id=4 AND t.production_year>2003;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_id=98;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<29028;
SELECT COUNT(*) FROM title t WHERE t.kind_id<7 AND t.production_year<1969;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_id>5;
SELECT COUNT(*) FROM title t WHERE t.kind_id=7 AND t.production_year=1991;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_id=15;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id>531768;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>3673;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<20205;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id>687 AND mc.company_type_id>1;
SELECT COUNT(*) FROM title t WHERE t.kind_id=1;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_id<16;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<5449;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_id>7;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_id=4;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<37386;
SELECT COUNT(*) FROM title t WHERE t.kind_id<7 AND t.production_year>0;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id>73217 AND mc.company_type_id>1;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<3511;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id>49970;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<3721572 AND ci.role_id=3;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>4097;
SELECT COUNT(*) FROM title t WHERE t.kind_id>1 AND t.production_year<1955;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<19 AND mc.company_type_id=1;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id=1837760;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_id=3;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_id=89;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_id>3;
SELECT COUNT(*) FROM movie_companies mc,title t WHERE t.id=mc.movie_id AND mc.company_id=11369;
SELECT COUNT(*) FROM movie_info mi,title t WHERE t.id=mi.movie_id;
SELECT COUNT(*) FROM movie_companies mc,title t WHERE t.id=mc.movie_id AND t.kind_id<7;
SELECT COUNT(*) FROM movie_info_idx mi_idx,title t WHERE t.id=mi_idx.movie_id AND mi_idx.info_type_id=99 AND t.kind_id>4 AND t.production_year>2001;
SELECT COUNT(*) FROM cast_info ci,title t WHERE t.id=ci.movie_id AND t.kind_id=1;
SELECT COUNT(*) FROM movie_info_idx mi_idx,title t WHERE t.id=mi_idx.movie_id AND t.kind_id<7;
SELECT COUNT(*) FROM movie_keyword mk,title t WHERE t.id=mk.movie_id AND mk.keyword_id<6778 AND t.kind_id=7;
SELECT COUNT(*) FROM cast_info ci,title t WHERE t.id=ci.movie_id AND ci.person_id<699056 AND t.kind_id=3 AND t.production_year<2012;
SELECT COUNT(*) FROM movie_info_idx mi_idx,title t WHERE t.id=mi_idx.movie_id AND mi_idx.info_type_id>100;
SELECT COUNT(*) FROM movie_info_idx mi_idx,title t WHERE t.id=mi_idx.movie_id AND mi_idx.info_type_id<101 AND t.kind_id>3 AND t.production_year<2004;
SELECT COUNT(*) FROM movie_companies mc,title t WHERE t.id=mc.movie_id AND mc.company_id>70637 AND t.kind_id=1 AND t.production_year=1979;
SELECT COUNT(*) FROM movie_info mi,title t WHERE t.id=mi.movie_id AND mi.info_type_id=3 AND t.kind_id<7 AND t.production_year<2010;
SELECT COUNT(*) FROM movie_info_idx mi_idx,title t WHERE t.id=mi_idx.movie_id;
SELECT COUNT(*) FROM movie_info_idx mi_idx,title t WHERE t.id=mi_idx.movie_id AND t.kind_id>1 AND t.production_year=1998;
SELECT COUNT(*) FROM movie_info mi,title t WHERE t.id=mi.movie_id AND mi.info_type_id=2 AND t.kind_id<2;
SELECT COUNT(*) FROM cast_info ci,title t WHERE t.id=ci.movie_id AND ci.person_id<3673491 AND ci.role_id<2;
SELECT COUNT(*) FROM cast_info ci,title t WHERE t.id=ci.movie_id AND ci.person_id>1501023 AND t.kind_id<7;
SELECT COUNT(*) FROM movie_companies mc,title t WHERE t.id=mc.movie_id AND t.kind_id<7 AND t.production_year=1927;
SELECT COUNT(*) FROM movie_info mi,title t WHERE t.id=mi.movie_id AND t.kind_id<4;
SELECT COUNT(*) FROM movie_keyword mk,title t WHERE t.id=mk.movie_id AND mk.keyword_id=17086 AND t.kind_id>1;
SELECT COUNT(*) FROM cast_info ci,title t WHERE t.id=ci.movie_id;
SELECT COUNT(*) FROM cast_info ci,title t WHERE t.id=ci.movie_id AND ci.person_id>1440894 AND ci.role_id<6;
SELECT COUNT(*) FROM movie_keyword mk,title t WHERE t.id=mk.movie_id AND t.kind_id=7 AND t.production_year=1963;
SELECT COUNT(*) FROM movie_companies mc,title t WHERE t.id=mc.movie_id AND mc.company_id>99227 AND t.kind_id=1;
SELECT COUNT(*) FROM cast_info ci,title t WHERE t.id=ci.movie_id AND ci.person_id>1343313 AND ci.role_id<5 AND t.kind_id<7 AND t.production_year>1952;
SELECT COUNT(*) FROM movie_keyword mk,title t WHERE t.id=mk.movie_id AND mk.keyword_id<114328 AND t.kind_id=7 AND t.production_year>2002;
SELECT COUNT(*) FROM movie_info mi,title t WHERE t.id=mi.movie_id AND mi.info_type_id=7 AND t.kind_id<3 AND t.production_year<1995;
SELECT COUNT(*) FROM cast_info ci,title t WHERE t.id=ci.movie_id AND ci.person_id<2186779 AND ci.role_id>1;
SELECT COUNT(*) FROM movie_info mi,title t WHERE t.id=mi.movie_id AND mi.info_type_id>94;
SELECT COUNT(*) FROM cast_info ci,title t WHERE t.id=ci.movie_id AND t.kind_id<7 AND t.production_year>2008;
SELECT COUNT(*) FROM movie_info_idx mi_idx,title t WHERE t.id=mi_idx.movie_id AND mi_idx.info_type_id=99;
SELECT COUNT(*) FROM movie_info mi,title t WHERE t.id=mi.movie_id AND mi.info_type_id=2;
SELECT COUNT(*) FROM movie_keyword mk,title t WHERE t.id=mk.movie_id AND mk.keyword_id=4609 AND t.kind_id<7;
SELECT COUNT(*) FROM movie_info_idx mi_idx,title t WHERE t.id=mi_idx.movie_id AND mi_idx.info_type_id<101 AND t.kind_id<4 AND t.production_year>2004;
SELECT COUNT(*) FROM movie_keyword mk,title t WHERE t.id=mk.movie_id;
SELECT COUNT(*) FROM movie_info_idx mi_idx,title t WHERE t.id=mi_idx.movie_id AND t.kind_id>1;
SELECT COUNT(*) FROM movie_companies mc,title t WHERE t.id=mc.movie_id AND t.kind_id=1 AND t.production_year>2008;
SELECT COUNT(*) FROM movie_companies mc,title t WHERE t.id=mc.movie_id;
SELECT COUNT(*) FROM movie_info_idx mi_idx,title t WHERE t.id=mi_idx.movie_id AND t.kind_id=7 AND t.production_year>2010;
SELECT COUNT(*) FROM movie_companies mc,title t WHERE t.id=mc.movie_id AND mc.company_id<27054 AND t.kind_id=7;
SELECT COUNT(*) FROM movie_info mi,title t WHERE t.id=mi.movie_id AND t.kind_id=1 AND t.production_year<2005;
SELECT COUNT(*) FROM movie_info mi,title t WHERE t.id=mi.movie_id AND mi.info_type_id<8 AND t.kind_id<3;
SELECT COUNT(*) FROM movie_info_idx mi_idx,title t WHERE t.id=mi_idx.movie_id AND mi_idx.info_type_id>101;
SELECT COUNT(*) FROM cast_info ci,title t WHERE t.id=ci.movie_id AND ci.person_id>1336833 AND t.kind_id=4;
SELECT COUNT(*) FROM movie_info mi,title t WHERE t.id=mi.movie_id AND mi.info_type_id>2 AND t.kind_id<4;
SELECT COUNT(*) FROM movie_info mi,title t WHERE t.id=mi.movie_id AND t.kind_id=4 AND t.production_year>2003;
SELECT COUNT(*) FROM movie_info mi,title t WHERE t.id=mi.movie_id AND mi.info_type_id<15;
SELECT COUNT(*) FROM movie_info_idx mi_idx,title t WHERE t.id=mi_idx.movie_id AND mi_idx.info_type_id=99 AND t.kind_id=3 AND t.production_year<2002;
SELECT COUNT(*) FROM cast_info ci,title t WHERE t.id=ci.movie_id AND ci.person_id>2674310 AND ci.role_id>3 AND t.kind_id=7 AND t.production_year=1998;
SELECT COUNT(*) FROM movie_companies mc,title t WHERE t.id=mc.movie_id AND mc.company_id<262;
SELECT COUNT(*) FROM movie_info mi,title t WHERE t.id=mi.movie_id AND mi.info_type_id<4 AND t.kind_id=7 AND t.production_year>2004;
SELECT COUNT(*) FROM movie_companies mc,title t WHERE t.id=mc.movie_id AND mc.company_id<11238 AND t.kind_id=2;
SELECT COUNT(*) FROM movie_companies mc,title t WHERE t.id=mc.movie_id AND t.kind_id<7 AND t.production_year=1997;
SELECT COUNT(*) FROM movie_info_idx mi_idx,title t WHERE t.id=mi_idx.movie_id AND t.kind_id=7;
SELECT COUNT(*) FROM movie_companies mc,title t WHERE t.id=mc.movie_id AND mc.company_id>687 AND t.kind_id=1 AND t.production_year>1996;
SELECT COUNT(*) FROM cast_info ci,title t WHERE t.id=ci.movie_id AND ci.person_id>345682 AND ci.role_id=1 AND t.kind_id>1 AND t.production_year=1994;
SELECT COUNT(*) FROM movie_companies mc,title t WHERE t.id=mc.movie_id AND t.kind_id>1;
SELECT COUNT(*) FROM movie_info mi,title t WHERE t.id=mi.movie_id AND mi.info_type_id=15 AND t.kind_id<7;
SELECT COUNT(*) FROM movie_companies mc,title t WHERE t.id=mc.movie_id AND mc.company_id<145 AND mc.company_type_id=1;
SELECT COUNT(*) FROM movie_info mi,title t WHERE t.id=mi.movie_id AND mi.info_type_id=4 AND t.kind_id<7;
SELECT COUNT(*) FROM movie_keyword mk,title t WHERE t.id=mk.movie_id AND t.kind_id=7 AND t.production_year>1976;
SELECT COUNT(*) FROM movie_companies mc,title t WHERE t.id=mc.movie_id AND mc.company_id>2065;
SELECT COUNT(*) FROM movie_keyword mk,title t WHERE t.id=mk.movie_id AND t.kind_id=7 AND t.production_year>2003;
SELECT COUNT(*) FROM movie_info mi,title t WHERE t.id=mi.movie_id AND mi.info_type_id<6 AND t.kind_id<7;
SELECT COUNT(*) FROM movie_companies mc,title t WHERE t.id=mc.movie_id AND t.kind_id=7;
SELECT COUNT(*) FROM cast_info ci,title t WHERE t.id=ci.movie_id AND ci.person_id>3578081 AND t.kind_id=1;
SELECT COUNT(*) FROM movie_companies mc,title t WHERE t.id=mc.movie_id AND mc.company_id>13114 AND mc.company_type_id<2;
SELECT COUNT(*) FROM movie_keyword mk,title t WHERE t.id=mk.movie_id AND mk.keyword_id>9329 AND t.kind_id=7;
SELECT COUNT(*) FROM movie_info mi,title t WHERE t.id=mi.movie_id AND mi.info_type_id<16;
SELECT COUNT(*) FROM movie_info_idx mi_idx,title t WHERE t.id=mi_idx.movie_id AND mi_idx.info_type_id<101 AND t.kind_id>1;
SELECT COUNT(*) FROM movie_keyword mk,title t WHERE t.id=mk.movie_id AND t.kind_id<7;
SELECT COUNT(*) FROM movie_info mi,title t WHERE t.id=mi.movie_id AND mi.info_type_id<8 AND t.kind_id>1 AND t.production_year>2011;
SELECT COUNT(*) FROM movie_companies mc,title t WHERE t.id=mc.movie_id AND mc.company_id=819 AND mc.company_type_id<2 AND t.kind_id=7;
SELECT COUNT(*) FROM movie_info mi,title t WHERE t.id=mi.movie_id AND mi.info_type_id=16;
SELECT COUNT(*) FROM movie_companies mc,title t WHERE t.id=mc.movie_id AND mc.company_id<45801 AND mc.company_type_id<2;
SELECT COUNT(*) FROM cast_info ci,title t WHERE t.id=ci.movie_id AND ci.person_id<766648;
SELECT COUNT(*) FROM movie_info_idx mi_idx,title t WHERE t.id=mi_idx.movie_id AND mi_idx.info_type_id>100 AND t.kind_id>4 AND t.production_year=1989;
SELECT COUNT(*) FROM cast_info ci,title t WHERE t.id=ci.movie_id AND ci.person_id=446805 AND ci.role_id>3;
SELECT COUNT(*) FROM movie_keyword mk,title t WHERE t.id=mk.movie_id AND mk.keyword_id=4649;
SELECT COUNT(*) FROM movie_info mi,title t WHERE t.id=mi.movie_id AND t.kind_id=7;
SELECT COUNT(*) FROM movie_companies mc,title t WHERE t.id=mc.movie_id AND mc.company_id<13912 AND t.kind_id=7;
SELECT COUNT(*) FROM movie_info mi,title t WHERE t.id=mi.movie_id AND mi.info_type_id=7 AND t.kind_id=4 AND t.production_year>2013;
SELECT COUNT(*) FROM movie_info mi,title t WHERE t.id=mi.movie_id AND mi.info_type_id=16 AND t.kind_id=1 AND t.production_year<1971;
SELECT COUNT(*) FROM movie_keyword mk,title t WHERE t.id=mk.movie_id AND mk.keyword_id=21101 AND t.kind_id<7;
SELECT COUNT(*) FROM cast_info ci,title t WHERE t.id=ci.movie_id AND ci.person_id<2202179;
SELECT COUNT(*) FROM movie_keyword mk,title t WHERE t.id=mk.movie_id AND t.kind_id<2;
SELECT COUNT(*) FROM movie_keyword mk,title t WHERE t.id=mk.movie_id AND mk.keyword_id=5108;
SELECT COUNT(*) FROM cast_info ci,title t WHERE t.id=ci.movie_id AND t.kind_id<7;
SELECT COUNT(*) FROM movie_info_idx mi_idx,title t WHERE t.id=mi_idx.movie_id AND t.kind_id=1;
SELECT COUNT(*) FROM movie_info mi,title t WHERE t.id=mi.movie_id AND mi.info_type_id=8 AND t.kind_id>1;
SELECT COUNT(*) FROM movie_companies mc,title t WHERE t.id=mc.movie_id AND mc.company_id>707;
SELECT COUNT(*) FROM movie_info mi,title t WHERE t.id=mi.movie_id AND mi.info_type_id>18 AND t.kind_id=7;
SELECT COUNT(*) FROM movie_info mi,title t WHERE t.id=mi.movie_id AND t.kind_id=1 AND t.production_year>2010;
SELECT COUNT(*) FROM movie_info_idx mi_idx,title t WHERE t.id=mi_idx.movie_id AND mi_idx.info_type_id<101;
SELECT COUNT(*) FROM movie_info_idx mi_idx,title t WHERE t.id=mi_idx.movie_id AND mi_idx.info_type_id>100 AND t.kind_id>4;
SELECT COUNT(*) FROM movie_companies mc,title t WHERE t.id=mc.movie_id AND mc.company_id=75641 AND t.kind_id<7;
SELECT COUNT(*) FROM cast_info ci,title t WHERE t.id=ci.movie_id AND ci.person_id<2962305 AND ci.role_id=2;
SELECT COUNT(*) FROM movie_keyword mk,title t WHERE t.id=mk.movie_id AND mk.keyword_id>14662;
SELECT COUNT(*) FROM movie_info mi,title t WHERE t.id=mi.movie_id AND t.kind_id<7;
SELECT COUNT(*) FROM movie_info mi,title t WHERE t.id=mi.movie_id AND mi.info_type_id>18 AND t.kind_id=7 AND t.production_year=2010;
SELECT COUNT(*) FROM movie_info mi,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=mi.movie_id;
SELECT COUNT(*) FROM cast_info ci,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=ci.movie_id;
SELECT COUNT(*) FROM movie_companies mc,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mc.movie_id AND mc.company_id>11376 AND t.kind_id=7 AND t.production_year>2011;
SELECT COUNT(*) FROM movie_info mi,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mi.movie_id AND mi.info_type_id>16 AND ci.person_id=3552871;
SELECT COUNT(*) FROM cast_info ci,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=ci.movie_id AND ci.person_id<887377;
SELECT COUNT(*) FROM cast_info ci,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=ci.movie_id AND ci.person_id>2869783 AND ci.role_id>2 AND t.kind_id=7 AND mi.info_type_id>2;
SELECT COUNT(*) FROM movie_keyword mk,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=mk.movie_id;
SELECT COUNT(*) FROM movie_keyword mk,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND mk.keyword_id<178 AND t.kind_id<7 AND t.production_year>1988;
SELECT COUNT(*) FROM cast_info ci,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=ci.movie_id AND ci.person_id<3673491 AND ci.role_id<2;
SELECT COUNT(*) FROM movie_keyword mk,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND mk.keyword_id<1915 AND t.kind_id=7;
SELECT COUNT(*) FROM movie_info mi,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi.movie_id AND mi.info_type_id=2 AND t.kind_id=7;
SELECT COUNT(*) FROM movie_info mi,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mi.movie_id AND mi.info_type_id=105;
SELECT COUNT(*) FROM movie_companies mc,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mc.movie_id AND t.kind_id>1 AND ci.person_id<822307 AND ci.role_id=1;
SELECT COUNT(*) FROM movie_info_idx mi_idx,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi_idx.movie_id;
SELECT COUNT(*) FROM cast_info ci,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=ci.movie_id AND ci.person_id>2364119 AND ci.role_id=10 AND t.kind_id<7;
SELECT COUNT(*) FROM cast_info ci,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=ci.movie_id AND ci.person_id<3053817 AND ci.role_id=1 AND t.kind_id>1 AND t.production_year<2005 AND mi.info_type_id<16;
SELECT COUNT(*) FROM movie_info mi,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mi.movie_id;
SELECT COUNT(*) FROM movie_info mi,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi.movie_id AND mi.info_type_id>7 AND mk.keyword_id>71;
SELECT COUNT(*) FROM movie_info_idx mi_idx,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND mi_idx.info_type_id=99 AND mi.info_type_id>16;
SELECT COUNT(*) FROM cast_info ci,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=ci.movie_id AND ci.person_id>2783202 AND t.kind_id>1 AND mi.info_type_id<4;
SELECT COUNT(*) FROM movie_keyword mk,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND mk.keyword_id=2375 AND t.kind_id>1;
SELECT COUNT(*) FROM movie_companies mc,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mc.movie_id AND mk.keyword_id<3662;
SELECT COUNT(*) FROM movie_companies mc,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mc.movie_id AND mc.company_id=96569 AND mc.company_type_id>1 AND t.kind_id<7 AND t.production_year<2007 AND mi.info_type_id<8;
SELECT COUNT(*) FROM cast_info ci,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=ci.movie_id AND ci.person_id>3218597 AND ci.role_id>4;
SELECT COUNT(*) FROM movie_info_idx mi_idx,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.kind_id<7 AND mi.info_type_id>16;
SELECT COUNT(*) FROM cast_info ci,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=ci.movie_id AND ci.person_id=898110 AND mc.company_id<14513 AND mc.company_type_id<2;
SELECT COUNT(*) FROM movie_info_idx mi_idx,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.kind_id>1 AND mi.info_type_id>16;
SELECT COUNT(*) FROM movie_keyword mk,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND mk.keyword_id>4102 AND t.kind_id<7 AND t.production_year>2011;
SELECT COUNT(*) FROM movie_companies mc,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mc.movie_id AND t.kind_id<7 AND ci.person_id=140130;
SELECT COUNT(*) FROM movie_info_idx mi_idx,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mi_idx.movie_id AND t.kind_id=4 AND ci.person_id>2321402 AND ci.role_id>3;
SELECT COUNT(*) FROM movie_info mi,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND mi.info_type_id<16 AND t.kind_id<7;
SELECT COUNT(*) FROM cast_info ci,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=ci.movie_id AND ci.person_id=3964881 AND t.kind_id=1 AND t.production_year<2010 AND mi_idx.info_type_id=99;
SELECT COUNT(*) FROM movie_keyword mk,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mk.movie_id;
SELECT COUNT(*) FROM movie_companies mc,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mc.movie_id AND mc.company_id=15226;
SELECT COUNT(*) FROM movie_companies mc,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mc.movie_id;
SELECT COUNT(*) FROM movie_info mi,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND mi.info_type_id>15 AND t.kind_id=7 AND mc.company_id<53178;
SELECT COUNT(*) FROM movie_info_idx mi_idx,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi_idx.movie_id AND mi_idx.info_type_id=100;
SELECT COUNT(*) FROM movie_companies mc,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mc.movie_id AND mc.company_id<145 AND mc.company_type_id=1;
SELECT COUNT(*) FROM movie_info mi,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND mc.company_id=72650;
SELECT COUNT(*) FROM movie_info mi,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi.movie_id AND mi.info_type_id>7;
SELECT COUNT(*) FROM movie_info mi,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi.movie_id AND mi.info_type_id=4 AND t.kind_id<7 AND mk.keyword_id<2477;
SELECT COUNT(*) FROM movie_info mi,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND mi.info_type_id<3;
SELECT COUNT(*) FROM movie_companies mc,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mc.movie_id AND t.kind_id=7 AND t.production_year>2009;
SELECT COUNT(*) FROM movie_companies mc,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mc.movie_id AND mc.company_id>5379 AND t.kind_id=7 AND t.production_year<1973;
SELECT COUNT(*) FROM movie_info mi,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi.movie_id AND mi.info_type_id>9 AND t.kind_id<2 AND t.production_year<2010;
SELECT COUNT(*) FROM movie_companies mc,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mc.movie_id AND mc.company_id=87965;
SELECT COUNT(*) FROM movie_companies mc,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mc.movie_id AND ci.person_id>2967387;
SELECT COUNT(*) FROM movie_info_idx mi_idx,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi_idx.movie_id AND mi_idx.info_type_id<100 AND t.kind_id<7 AND t.production_year>1919;
SELECT COUNT(*) FROM movie_info_idx mi_idx,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi_idx.movie_id AND mi_idx.info_type_id<101 AND t.kind_id>1 AND mk.keyword_id=10833;
SELECT COUNT(*) FROM movie_info_idx mi_idx,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id;
SELECT COUNT(*) FROM movie_info_idx mi_idx,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mi_idx.movie_id AND mi_idx.info_type_id=101 AND ci.person_id<2450667 AND ci.role_id>3;
SELECT COUNT(*) FROM movie_info_idx mi_idx,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mi_idx.movie_id AND t.kind_id=7 AND t.production_year>1967;
SELECT COUNT(*) FROM movie_keyword mk,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND mk.keyword_id>16264 AND mi_idx.info_type_id=101;
SELECT COUNT(*) FROM movie_companies mc,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mc.movie_id AND mc.company_id=2924 AND t.kind_id=7 AND t.production_year=2009 AND mi.info_type_id=4;
SELECT COUNT(*) FROM movie_info_idx mi_idx,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mi_idx.movie_id AND mi_idx.info_type_id>100 AND t.kind_id>4 AND t.production_year=1989 AND ci.person_id>1229314;
SELECT COUNT(*) FROM movie_keyword mk,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND mk.keyword_id=5925 AND t.kind_id=7;
SELECT COUNT(*) FROM movie_companies mc,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mc.movie_id AND mc.company_id=18664;
SELECT COUNT(*) FROM movie_keyword mk,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND mk.keyword_id=1901 AND t.kind_id=3 AND t.production_year<2011 AND mi.info_type_id<17;
SELECT COUNT(*) FROM cast_info ci,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=ci.movie_id AND t.kind_id<7;
SELECT COUNT(*) FROM cast_info ci,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=ci.movie_id AND ci.person_id=1370784;
SELECT COUNT(*) FROM movie_companies mc,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mc.movie_id AND mc.company_id=129931 AND mi_idx.info_type_id=100;
SELECT COUNT(*) FROM movie_info mi,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi.movie_id AND t.kind_id=7;
SELECT COUNT(*) FROM movie_info mi,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND mi.info_type_id=8 AND t.kind_id>1;
SELECT COUNT(*) FROM movie_info mi,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND mi.info_type_id=4 AND t.kind_id>1;
SELECT COUNT(*) FROM movie_companies mc,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mc.movie_id AND mi.info_type_id<6;
SELECT COUNT(*) FROM movie_companies mc,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mc.movie_id AND t.kind_id<7 AND ci.person_id>201466 AND ci.role_id=2;
SELECT COUNT(*) FROM cast_info ci,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=ci.movie_id AND mk.keyword_id<34174;
SELECT COUNT(*) FROM cast_info ci,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=ci.movie_id AND t.kind_id<7;
SELECT COUNT(*) FROM movie_keyword mk,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=mk.movie_id AND mk.keyword_id>14662 AND mc.company_id=11147 AND mc.company_type_id<2;
SELECT COUNT(*) FROM movie_info mi,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND t.kind_id<7 AND mc.company_id<170397;
SELECT COUNT(*) FROM movie_companies mc,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mc.movie_id AND mc.company_id=11153;
SELECT COUNT(*) FROM movie_keyword mk,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND t.kind_id<7;
SELECT COUNT(*) FROM movie_companies mc,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mc.movie_id AND t.kind_id=7 AND mi.info_type_id=16;
SELECT COUNT(*) FROM movie_keyword mk,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND t.kind_id=1 AND t.production_year>1998 AND mi_idx.info_type_id=100;
SELECT COUNT(*) FROM cast_info ci,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=ci.movie_id AND t.kind_id>1;
SELECT COUNT(*) FROM movie_info_idx mi_idx,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mi_idx.movie_id AND ci.person_id>301236 AND ci.role_id<10;
SELECT COUNT(*) FROM cast_info ci,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=ci.movie_id AND ci.person_id<976307 AND ci.role_id>2 AND t.kind_id<4 AND t.production_year>1995 AND mk.keyword_id>6887;
SELECT COUNT(*) FROM movie_info mi,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi.movie_id;
SELECT COUNT(*) FROM movie_info_idx mi_idx,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi_idx.movie_id AND t.kind_id=1 AND t.production_year=2005 AND mk.keyword_id<763;
SELECT COUNT(*) FROM movie_companies mc,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mc.movie_id AND mc.company_id<1130 AND t.kind_id<7 AND t.production_year=2001 AND mk.keyword_id<335;
SELECT COUNT(*) FROM cast_info ci,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=ci.movie_id AND ci.person_id>496474 AND ci.role_id>3 AND t.kind_id<3 AND t.production_year<2012 AND mi.info_type_id<7;
SELECT COUNT(*) FROM cast_info ci,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=ci.movie_id AND ci.person_id=2217294 AND ci.role_id>1 AND mk.keyword_id<7426;
SELECT COUNT(*) FROM movie_companies mc,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mc.movie_id AND mc.company_id<11153 AND mc.company_type_id>1;
SELECT COUNT(*) FROM movie_info mi,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mi.movie_id AND t.kind_id<7 AND mi_idx.info_type_id=101;
SELECT COUNT(*) FROM movie_keyword mk,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND mk.keyword_id=542 AND ci.person_id>1195448;
SELECT COUNT(*) FROM movie_keyword mk,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND mk.keyword_id>3599 AND t.kind_id<7 AND t.production_year<2009 AND ci.person_id=2436568 AND ci.role_id<7;
SELECT COUNT(*) FROM movie_info_idx mi_idx,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi_idx.movie_id AND t.kind_id=7 AND t.production_year<1994;
SELECT COUNT(*) FROM movie_info_idx mi_idx,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND mi_idx.info_type_id>101 AND t.kind_id<7;
SELECT COUNT(*) FROM movie_keyword mk,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=mk.movie_id AND mk.keyword_id<130000 AND t.kind_id<7 AND t.production_year<1972 AND mc.company_id>210399;
SELECT COUNT(*) FROM movie_companies mc,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mc.movie_id AND t.kind_id>1 AND t.production_year>2006 AND ci.person_id>2906319;
SELECT COUNT(*) FROM movie_info_idx mi_idx,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi_idx.movie_id AND mi_idx.info_type_id=100 AND t.kind_id=7;
SELECT COUNT(*) FROM movie_companies mc,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mc.movie_id AND t.kind_id>1 AND mk.keyword_id>1082;
SELECT COUNT(*) FROM movie_info mi,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mi.movie_id AND t.kind_id=7 AND ci.person_id>810611;
SELECT COUNT(*) FROM movie_keyword mk,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND t.kind_id=1 AND ci.person_id<664944;
SELECT COUNT(*) FROM cast_info ci,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=ci.movie_id AND ci.person_id<1423954 AND t.kind_id<7;
SELECT COUNT(*) FROM movie_keyword mk,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND t.kind_id=7 AND t.production_year=1975;
SELECT COUNT(*) FROM cast_info ci,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=ci.movie_id;
SELECT COUNT(*) FROM cast_info ci,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=ci.movie_id AND ci.person_id>1347118 AND ci.role_id>10;
SELECT COUNT(*) FROM movie_keyword mk,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=mk.movie_id AND mk.keyword_id<7549 AND t.kind_id<7;
SELECT COUNT(*) FROM movie_info_idx mi_idx,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=mi_idx.movie_id AND mi_idx.info_type_id>99 AND t.kind_id=2 AND t.production_year=1996 AND mc.company_id>4625 AND mc.company_type_id>1;
SELECT COUNT(*) FROM cast_info ci,movie_info mi,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND t.id=ci.movie_id AND mc.company_id<240;
SELECT COUNT(*) FROM movie_companies mc,movie_keyword mk,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND t.id=mc.movie_id AND mc.company_id=686 AND mc.company_type_id>1 AND t.kind_id<7 AND ci.person_id>788691 AND ci.role_id<9;
SELECT COUNT(*) FROM movie_keyword mk,movie_info_idx mi_idx,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.id=mk.movie_id AND mk.keyword_id<6778 AND mi_idx.info_type_id=99;
SELECT COUNT(*) FROM movie_info_idx mi_idx,movie_info mi,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mi.movie_id AND t.id=mi_idx.movie_id AND mi_idx.info_type_id=100 AND t.kind_id=3 AND t.production_year>2001 AND ci.person_id=2891815;
SELECT COUNT(*) FROM movie_info_idx mi_idx,cast_info ci,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=ci.movie_id AND t.id=mi_idx.movie_id AND mi_idx.info_type_id>99 AND ci.person_id<1316052 AND t.kind_id>1 AND mi.info_type_id=8;
SELECT COUNT(*) FROM movie_keyword mk,movie_info mi,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND t.id=mk.movie_id AND mi.info_type_id>16 AND mc.company_id<18009;
SELECT COUNT(*) FROM movie_companies mc,movie_keyword mk,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND t.id=mc.movie_id AND mk.keyword_id>8540 AND t.kind_id<7 AND t.production_year<1967;
SELECT COUNT(*) FROM movie_keyword mk,movie_info mi,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mi.movie_id AND t.id=mk.movie_id;
SELECT COUNT(*) FROM movie_info mi,movie_keyword mk,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND t.id=mi.movie_id AND mi.info_type_id=7 AND mk.keyword_id<2799 AND t.kind_id=1 AND ci.person_id<2900296 AND ci.role_id=3;
SELECT COUNT(*) FROM movie_info mi,movie_keyword mk,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND t.id=mi.movie_id AND mk.keyword_id<7771 AND t.kind_id=7 AND t.production_year=2012 AND ci.person_id<2400859;
SELECT COUNT(*) FROM cast_info ci,movie_keyword mk,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND t.id=ci.movie_id AND ci.person_id>2742209 AND ci.role_id<8 AND mk.keyword_id=2906 AND t.kind_id>1;
SELECT COUNT(*) FROM movie_keyword mk,movie_info_idx mi_idx,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.id=mk.movie_id AND mk.keyword_id<49236 AND t.kind_id=7 AND t.production_year>2010;
SELECT COUNT(*) FROM cast_info ci,movie_info mi,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mi.movie_id AND t.id=ci.movie_id AND ci.person_id>3705631 AND mi.info_type_id>2;
SELECT COUNT(*) FROM cast_info ci,movie_info mi,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi.movie_id AND t.id=ci.movie_id AND ci.person_id=167054 AND ci.role_id<3 AND mi.info_type_id<16;
SELECT COUNT(*) FROM cast_info ci,movie_keyword mk,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND t.id=ci.movie_id AND ci.person_id<2326252 AND mk.keyword_id>12352 AND t.kind_id>1 AND mi_idx.info_type_id<100;
SELECT COUNT(*) FROM movie_info mi,movie_keyword mk,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND t.id=mi.movie_id AND mk.keyword_id<4617 AND t.kind_id=4 AND t.production_year=1997;
SELECT COUNT(*) FROM movie_companies mc,movie_info_idx mi_idx,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.id=mc.movie_id AND mc.company_id>27 AND mc.company_type_id<2 AND t.kind_id=7 AND mi.info_type_id>2;
SELECT COUNT(*) FROM movie_info_idx mi_idx,movie_info mi,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.kind_id>1 AND t.production_year>1997;
SELECT COUNT(*) FROM movie_info_idx mi_idx,movie_keyword mk,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=mk.movie_id AND t.id=mi_idx.movie_id AND t.kind_id=7 AND t.production_year<2006;
SELECT COUNT(*) FROM movie_info mi,movie_companies mc,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mc.movie_id AND t.id=mi.movie_id AND t.kind_id=7 AND mi_idx.info_type_id=99;
SELECT COUNT(*) FROM cast_info ci,movie_info mi,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi.movie_id AND t.id=ci.movie_id AND ci.person_id<2541335 AND mi.info_type_id<16 AND t.kind_id>1 AND t.production_year>1964;
SELECT COUNT(*) FROM cast_info ci,movie_companies mc,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mc.movie_id AND t.id=ci.movie_id AND mc.company_id<11156 AND mi.info_type_id=4;
SELECT COUNT(*) FROM movie_keyword mk,cast_info ci,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=ci.movie_id AND t.id=mk.movie_id AND mk.keyword_id=53879 AND ci.person_id>796094 AND mi_idx.info_type_id<100;
SELECT COUNT(*) FROM movie_info mi,cast_info ci,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=ci.movie_id AND t.id=mi.movie_id;
SELECT COUNT(*) FROM movie_companies mc,movie_info mi,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mi.movie_id AND t.id=mc.movie_id AND t.kind_id<7 AND t.production_year=2011;
SELECT COUNT(*) FROM movie_companies mc,movie_info_idx mi_idx,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.id=mc.movie_id AND mc.company_id>11437 AND mc.company_type_id<2 AND mi_idx.info_type_id=100 AND mi.info_type_id>94;
SELECT COUNT(*) FROM movie_keyword mk,movie_companies mc,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mc.movie_id AND t.id=mk.movie_id AND mk.keyword_id>5150;
SELECT COUNT(*) FROM cast_info ci,movie_info mi,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi.movie_id AND t.id=ci.movie_id AND ci.person_id>1719110 AND mi.info_type_id=13 AND t.kind_id<4 AND t.production_year=2009 AND mk.keyword_id<70;
SELECT COUNT(*) FROM movie_keyword mk,movie_info_idx mi_idx,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mi_idx.movie_id AND t.id=mk.movie_id AND mi_idx.info_type_id=99 AND t.kind_id=7 AND t.production_year>1967;
SELECT COUNT(*) FROM movie_info_idx mi_idx,movie_keyword mk,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND t.id=mi_idx.movie_id AND mi_idx.info_type_id>100 AND t.kind_id<7;
SELECT COUNT(*) FROM cast_info ci,movie_info_idx mi_idx,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi_idx.movie_id AND t.id=ci.movie_id AND ci.person_id=976846 AND mi_idx.info_type_id>100 AND t.kind_id>1;
SELECT COUNT(*) FROM movie_info_idx mi_idx,movie_keyword mk,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND t.id=mi_idx.movie_id AND mi_idx.info_type_id<101 AND mi.info_type_id>17;
SELECT COUNT(*) FROM movie_info_idx mi_idx,movie_keyword mk,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND t.id=mi_idx.movie_id;
SELECT COUNT(*) FROM movie_info mi,movie_companies mc,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mc.movie_id AND t.id=mi.movie_id AND mc.company_id>19969 AND mc.company_type_id>1 AND mi_idx.info_type_id<100;
SELECT COUNT(*) FROM cast_info ci,movie_info mi,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mi.movie_id AND t.id=ci.movie_id AND mi.info_type_id>2 AND t.kind_id=7 AND t.production_year<2007 AND mi_idx.info_type_id=100;
SELECT COUNT(*) FROM movie_info mi,cast_info ci,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=ci.movie_id AND t.id=mi.movie_id AND mi.info_type_id<3 AND mk.keyword_id>29254;
SELECT COUNT(*) FROM cast_info ci,movie_keyword mk,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND t.id=ci.movie_id AND mk.keyword_id=498 AND t.kind_id<7;
SELECT COUNT(*) FROM movie_info_idx mi_idx,movie_info mi,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mi.movie_id AND t.id=mi_idx.movie_id AND ci.person_id>887534 AND ci.role_id>2;
SELECT COUNT(*) FROM cast_info ci,movie_companies mc,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mc.movie_id AND t.id=ci.movie_id AND mc.company_id>2172 AND t.kind_id<7;
SELECT COUNT(*) FROM movie_keyword mk,movie_info mi,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mi.movie_id AND t.id=mk.movie_id AND mi.info_type_id>3;
SELECT COUNT(*) FROM movie_companies mc,movie_info_idx mi_idx,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mi_idx.movie_id AND t.id=mc.movie_id AND mc.company_id>133 AND t.kind_id<7 AND t.production_year=1990 AND ci.person_id=2501191;
SELECT COUNT(*) FROM movie_info mi,cast_info ci,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=ci.movie_id AND t.id=mi.movie_id AND mi.info_type_id<6 AND t.kind_id=3 AND t.production_year<2011 AND mc.company_id<2805 AND mc.company_type_id>1;
SELECT COUNT(*) FROM movie_info_idx mi_idx,movie_keyword mk,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=mk.movie_id AND t.id=mi_idx.movie_id AND mi_idx.info_type_id<101 AND t.kind_id=1 AND t.production_year<1971 AND mc.company_id>2050 AND mc.company_type_id=2;
SELECT COUNT(*) FROM movie_companies mc,movie_info_idx mi_idx,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi_idx.movie_id AND t.id=mc.movie_id AND mi_idx.info_type_id=100 AND t.kind_id<7 AND t.production_year=2006;
SELECT COUNT(*) FROM movie_keyword mk,movie_info_idx mi_idx,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.id=mk.movie_id AND mk.keyword_id=1;
SELECT COUNT(*) FROM movie_info_idx mi_idx,movie_keyword mk,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND t.id=mi_idx.movie_id AND mk.keyword_id=8234;
SELECT COUNT(*) FROM movie_info mi,movie_keyword mk,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND t.id=mi.movie_id AND mi.info_type_id>7 AND mk.keyword_id>56 AND t.kind_id<3 AND mi_idx.info_type_id>101;
SELECT COUNT(*) FROM movie_keyword mk,movie_info mi,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mi.movie_id AND t.id=mk.movie_id AND mi_idx.info_type_id<100;
SELECT COUNT(*) FROM cast_info ci,movie_info mi,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND t.id=ci.movie_id AND ci.person_id<2888027 AND mi.info_type_id>18 AND t.kind_id=7 AND t.production_year=2010;
SELECT COUNT(*) FROM cast_info ci,movie_info mi,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mi.movie_id AND t.id=ci.movie_id AND mi.info_type_id>5;
SELECT COUNT(*) FROM cast_info ci,movie_keyword mk,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND t.id=ci.movie_id AND ci.person_id>1751949 AND t.kind_id=1 AND t.production_year=2010 AND mi_idx.info_type_id=99;
SELECT COUNT(*) FROM movie_keyword mk,movie_companies mc,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mc.movie_id AND t.id=mk.movie_id AND mk.keyword_id<927 AND t.kind_id<7 AND mi.info_type_id>18;
SELECT COUNT(*) FROM movie_info_idx mi_idx,movie_info mi,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi.movie_id AND t.id=mi_idx.movie_id AND mi_idx.info_type_id>100 AND mi.info_type_id<16;
SELECT COUNT(*) FROM movie_info mi,movie_keyword mk,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND t.id=mi.movie_id AND t.kind_id=7 AND t.production_year>2005;
SELECT COUNT(*) FROM movie_info mi,movie_info_idx mi_idx,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mi_idx.movie_id AND t.id=mi.movie_id AND t.kind_id=7;
SELECT COUNT(*) FROM movie_keyword mk,movie_info mi,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND t.id=mk.movie_id AND mc.company_id=12126;
SELECT COUNT(*) FROM cast_info ci,movie_keyword mk,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND t.id=ci.movie_id AND mk.keyword_id<383 AND t.kind_id>1;
SELECT COUNT(*) FROM movie_keyword mk,movie_info_idx mi_idx,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mi_idx.movie_id AND t.id=mk.movie_id AND mk.keyword_id=3729 AND ci.person_id<1615955;
SELECT COUNT(*) FROM movie_keyword mk,movie_info_idx mi_idx,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.id=mk.movie_id AND mk.keyword_id<26039;
SELECT COUNT(*) FROM cast_info ci,movie_info mi,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi.movie_id AND t.id=ci.movie_id AND ci.person_id>3461716 AND ci.role_id=10 AND t.kind_id=4 AND t.production_year=2003 AND mk.keyword_id<130000;
SELECT COUNT(*) FROM movie_info_idx mi_idx,movie_info mi,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi.movie_id AND t.id=mi_idx.movie_id AND mi_idx.info_type_id=100;
SELECT COUNT(*) FROM movie_keyword mk,movie_companies mc,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mc.movie_id AND t.id=mk.movie_id AND mk.keyword_id>117;
SELECT COUNT(*) FROM movie_companies mc,movie_keyword mk,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND t.id=mc.movie_id AND mc.company_id<33191 AND mc.company_type_id<2 AND t.kind_id<7 AND ci.person_id<2438390 AND ci.role_id=1;
SELECT COUNT(*) FROM cast_info ci,movie_info mi,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mi.movie_id AND t.id=ci.movie_id AND t.kind_id<7 AND t.production_year<2007 AND mi_idx.info_type_id=101;
SELECT COUNT(*) FROM cast_info ci,movie_info_idx mi_idx,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=mi_idx.movie_id AND t.id=ci.movie_id AND ci.person_id>1347118 AND ci.role_id>10 AND t.kind_id=1 AND mc.company_id<68902 AND mc.company_type_id<2;
SELECT COUNT(*) FROM cast_info ci,movie_companies mc,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mc.movie_id AND t.id=ci.movie_id;
SELECT COUNT(*) FROM movie_keyword mk,movie_info_idx mi_idx,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=mi_idx.movie_id AND t.id=mk.movie_id AND mi_idx.info_type_id=101;
SELECT COUNT(*) FROM movie_keyword mk,movie_companies mc,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mc.movie_id AND t.id=mk.movie_id AND mk.keyword_id=52 AND mc.company_id<297 AND mi.info_type_id=16;
SELECT COUNT(*) FROM movie_info_idx mi_idx,movie_keyword mk,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND t.id=mi_idx.movie_id AND t.kind_id=1 AND ci.person_id=2932426;
SELECT COUNT(*) FROM movie_keyword mk,movie_companies mc,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mc.movie_id AND t.id=mk.movie_id AND mc.company_id<11373 AND t.kind_id=7;
SELECT COUNT(*) FROM movie_info_idx mi_idx,cast_info ci,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=ci.movie_id AND t.id=mi_idx.movie_id AND mi_idx.info_type_id>99 AND ci.person_id<2739777 AND t.kind_id<6 AND t.production_year<2001 AND mc.company_id<656;
SELECT COUNT(*) FROM movie_info_idx mi_idx,cast_info ci,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=ci.movie_id AND t.id=mi_idx.movie_id AND ci.person_id<3104799 AND ci.role_id<4 AND mk.keyword_id>15893;
SELECT COUNT(*) FROM movie_info_idx mi_idx,cast_info ci,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=ci.movie_id AND t.id=mi_idx.movie_id AND ci.person_id<900303;
SELECT COUNT(*) FROM cast_info ci,movie_keyword mk,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND t.id=ci.movie_id AND ci.person_id>3964371 AND t.kind_id=7 AND t.production_year=2005 AND mi_idx.info_type_id<100;
SELECT COUNT(*) FROM cast_info ci,movie_info mi,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi.movie_id AND t.id=ci.movie_id AND ci.person_id=1137716 AND ci.role_id>4 AND t.kind_id<7 AND mk.keyword_id<875;
SELECT COUNT(*) FROM movie_companies mc,movie_info_idx mi_idx,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mi_idx.movie_id AND t.id=mc.movie_id AND mc.company_id<91754 AND t.kind_id=7 AND t.production_year=2008;
SELECT COUNT(*) FROM cast_info ci,movie_info mi,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi.movie_id AND t.id=ci.movie_id AND mi.info_type_id=7 AND mk.keyword_id=6848;
SELECT COUNT(*) FROM movie_info_idx mi_idx,cast_info ci,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=ci.movie_id AND t.id=mi_idx.movie_id AND ci.person_id<2832365 AND t.kind_id>1 AND mi.info_type_id<16;
SELECT COUNT(*) FROM movie_info mi,movie_info_idx mi_idx,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi_idx.movie_id AND t.id=mi.movie_id AND t.kind_id<7 AND mk.keyword_id<870;
SELECT COUNT(*) FROM movie_keyword mk,movie_info_idx mi_idx,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mi_idx.movie_id AND t.id=mk.movie_id AND mi_idx.info_type_id=100 AND t.kind_id<7 AND t.production_year>2003;
SELECT COUNT(*) FROM movie_companies mc,movie_info_idx mi_idx,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.id=mc.movie_id AND mc.company_id<774;
SELECT COUNT(*) FROM cast_info ci,movie_companies mc,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mc.movie_id AND t.id=ci.movie_id AND ci.person_id>317132 AND ci.role_id<2;
SELECT COUNT(*) FROM movie_info_idx mi_idx,cast_info ci,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=ci.movie_id AND t.id=mi_idx.movie_id AND ci.person_id<761388 AND ci.role_id=3 AND mi.info_type_id>4;
SELECT COUNT(*) FROM movie_info_idx mi_idx,cast_info ci,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=ci.movie_id AND t.id=mi_idx.movie_id AND ci.person_id>1091187;
SELECT COUNT(*) FROM cast_info ci,movie_info mi,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi.movie_id AND t.id=ci.movie_id AND mk.keyword_id>2549;
SELECT COUNT(*) FROM movie_companies mc,movie_info_idx mi_idx,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi_idx.movie_id AND t.id=mc.movie_id AND mc.company_id=711 AND mk.keyword_id<12540;
SELECT COUNT(*) FROM movie_info mi,movie_info_idx mi_idx,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi_idx.movie_id AND t.id=mi.movie_id AND mi.info_type_id<18 AND t.kind_id>1 AND mk.keyword_id=17380;
SELECT COUNT(*) FROM cast_info ci,movie_info mi,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mi.movie_id AND t.id=ci.movie_id AND ci.person_id=2781182 AND mi.info_type_id=4;
SELECT COUNT(*) FROM movie_info_idx mi_idx,movie_info mi,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi.movie_id AND t.id=mi_idx.movie_id AND mi_idx.info_type_id=99;
SELECT COUNT(*) FROM movie_keyword mk,cast_info ci,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=ci.movie_id AND t.id=mk.movie_id AND mk.keyword_id<63677 AND ci.person_id>2824229 AND t.kind_id=2 AND t.production_year>2011 AND mi.info_type_id<7;
SELECT COUNT(*) FROM movie_info mi,movie_companies mc,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mc.movie_id AND t.id=mi.movie_id AND mc.company_id=1782;
SELECT COUNT(*) FROM movie_companies mc,movie_keyword mk,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND t.id=mc.movie_id AND t.kind_id<7 AND t.production_year=2013;
SELECT COUNT(*) FROM movie_info_idx mi_idx,movie_companies mc,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mc.movie_id AND t.id=mi_idx.movie_id AND mc.company_id<19 AND mi.info_type_id=3;
SELECT COUNT(*) FROM movie_keyword mk,movie_info mi,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mi.movie_id AND t.id=mk.movie_id AND mk.keyword_id<20948 AND mi.info_type_id>105 AND t.kind_id<7 AND t.production_year=1978 AND ci.person_id<1793126 AND ci.role_id>10;
SELECT COUNT(*) FROM cast_info ci,movie_keyword mk,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND t.id=ci.movie_id AND ci.person_id>900419 AND mk.keyword_id<22407 AND t.kind_id>1 AND t.production_year>2009 AND mi.info_type_id>16;
SELECT COUNT(*) FROM movie_companies mc,movie_info mi,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi.movie_id AND t.id=mc.movie_id AND mi.info_type_id<4 AND mk.keyword_id>62909;
SELECT COUNT(*) FROM movie_info mi,movie_info_idx mi_idx,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mi_idx.movie_id AND t.id=mi.movie_id AND mi.info_type_id<3 AND mi_idx.info_type_id=100 AND t.kind_id>1 AND t.production_year<2005 AND ci.person_id<1171258;
SELECT COUNT(*) FROM cast_info ci,movie_info_idx mi_idx,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi_idx.movie_id AND t.id=ci.movie_id AND ci.person_id=613413 AND ci.role_id<8 AND mi_idx.info_type_id=100;
SELECT COUNT(*) FROM movie_keyword mk,movie_info_idx mi_idx,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=mi_idx.movie_id AND t.id=mk.movie_id AND mi_idx.info_type_id<101 AND mc.company_id<11496;
SELECT COUNT(*) FROM movie_info_idx mi_idx,movie_companies mc,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mc.movie_id AND t.id=mi_idx.movie_id AND mc.company_id=12078 AND mk.keyword_id<30259;
SELECT COUNT(*) FROM movie_keyword mk,movie_info_idx mi_idx,movie_info mi,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.id=mk.movie_id AND mi_idx.info_type_id>101 AND ci.person_id<2409611 AND ci.role_id>10;
SELECT COUNT(*) FROM movie_companies mc,movie_info mi,movie_keyword mk,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND t.id=mi.movie_id AND t.id=mc.movie_id AND mc.company_id>70637 AND mi.info_type_id=8;
SELECT COUNT(*) FROM cast_info ci,movie_companies mc,movie_keyword mk,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND t.id=mc.movie_id AND t.id=ci.movie_id AND mc.company_id<18009 AND mi.info_type_id>3;
SELECT COUNT(*) FROM movie_info mi,movie_keyword mk,cast_info ci,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=ci.movie_id AND t.id=mk.movie_id AND t.id=mi.movie_id AND mi.info_type_id<16 AND ci.person_id<2019164 AND t.kind_id<7 AND t.production_year<1962;
SELECT COUNT(*) FROM movie_keyword mk,movie_info_idx mi_idx,movie_companies mc,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mc.movie_id AND t.id=mi_idx.movie_id AND t.id=mk.movie_id AND mi_idx.info_type_id=99 AND mc.company_id>15 AND t.kind_id<7 AND t.production_year>2008 AND mi.info_type_id>7;
SELECT COUNT(*) FROM movie_keyword mk,cast_info ci,movie_companies mc,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mc.movie_id AND t.id=ci.movie_id AND t.id=mk.movie_id AND mk.keyword_id=8688 AND ci.person_id>174349 AND ci.role_id<10 AND mc.company_id<3263 AND mc.company_type_id=2 AND mi.info_type_id>106;
SELECT COUNT(*) FROM cast_info ci,movie_keyword mk,movie_companies mc,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mc.movie_id AND t.id=mk.movie_id AND t.id=ci.movie_id AND ci.person_id<1342799 AND ci.role_id<10 AND mk.keyword_id<18242 AND mi.info_type_id<2;
SELECT COUNT(*) FROM movie_keyword mk,movie_info_idx mi_idx,movie_companies mc,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mc.movie_id AND t.id=mi_idx.movie_id AND t.id=mk.movie_id AND mi_idx.info_type_id<101 AND mc.company_id>115251 AND t.kind_id>1 AND mi.info_type_id<4;
SELECT COUNT(*) FROM movie_companies mc,movie_info mi,movie_keyword mk,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND t.id=mi.movie_id AND t.id=mc.movie_id AND mc.company_id<95587 AND mc.company_type_id>1 AND mi.info_type_id=16 AND t.kind_id<7 AND ci.person_id<1340395;
SELECT COUNT(*) FROM movie_info mi,movie_keyword mk,cast_info ci,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=ci.movie_id AND t.id=mk.movie_id AND t.id=mi.movie_id AND ci.person_id>2910756 AND ci.role_id>3 AND t.kind_id=1 AND t.production_year=2009 AND mi_idx.info_type_id=100;
SELECT COUNT(*) FROM cast_info ci,movie_companies mc,movie_keyword mk,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND t.id=mc.movie_id AND t.id=ci.movie_id AND ci.person_id>890982 AND mk.keyword_id=16686;
SELECT COUNT(*) FROM cast_info ci,movie_companies mc,movie_info_idx mi_idx,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.id=mc.movie_id AND t.id=ci.movie_id AND ci.person_id>1290114 AND mc.company_id>312 AND t.kind_id=7 AND t.production_year<2012;
SELECT COUNT(*) FROM movie_info_idx mi_idx,movie_info mi,movie_companies mc,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mc.movie_id AND t.id=mi.movie_id AND t.id=mi_idx.movie_id AND mi.info_type_id<16 AND mc.company_id<596 AND t.kind_id<7 AND t.production_year>1999 AND ci.person_id>2059310 AND ci.role_id=2;
SELECT COUNT(*) FROM movie_info mi,movie_info_idx mi_idx,movie_keyword mk,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=mk.movie_id AND t.id=mi_idx.movie_id AND t.id=mi.movie_id AND mi.info_type_id=98 AND mi_idx.info_type_id>101;
SELECT COUNT(*) FROM movie_info_idx mi_idx,cast_info ci,movie_companies mc,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mc.movie_id AND t.id=ci.movie_id AND t.id=mi_idx.movie_id AND mi_idx.info_type_id>99 AND t.kind_id=3 AND t.production_year<2002;
SELECT COUNT(*) FROM movie_info_idx mi_idx,cast_info ci,movie_info mi,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND t.id=ci.movie_id AND t.id=mi_idx.movie_id AND mi.info_type_id<16 AND mc.company_id>352 AND mc.company_type_id>1;
SELECT COUNT(*) FROM movie_info mi,movie_companies mc,movie_keyword mk,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND t.id=mc.movie_id AND t.id=mi.movie_id AND mi.info_type_id=6 AND mc.company_id<11238 AND mk.keyword_id=335;
SELECT COUNT(*) FROM cast_info ci,movie_companies mc,movie_info mi,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mi.movie_id AND t.id=mc.movie_id AND t.id=ci.movie_id AND ci.person_id<1885426 AND ci.role_id=1 AND mi.info_type_id>104 AND t.kind_id=1 AND t.production_year>1996;
SELECT COUNT(*) FROM movie_info mi,movie_companies mc,movie_info_idx mi_idx,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi_idx.movie_id AND t.id=mc.movie_id AND t.id=mi.movie_id AND mc.company_id=549;
SELECT COUNT(*) FROM movie_info_idx mi_idx,cast_info ci,movie_keyword mk,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND t.id=ci.movie_id AND t.id=mi_idx.movie_id AND mi_idx.info_type_id=100 AND t.kind_id=7 AND mi.info_type_id<4;
SELECT COUNT(*) FROM movie_info_idx mi_idx,movie_info mi,movie_keyword mk,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND t.id=mi.movie_id AND t.id=mi_idx.movie_id AND mi_idx.info_type_id>100 AND mk.keyword_id<32355 AND ci.person_id=2457750;
SELECT COUNT(*) FROM movie_info mi,movie_info_idx mi_idx,cast_info ci,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=ci.movie_id AND t.id=mi_idx.movie_id AND t.id=mi.movie_id AND ci.person_id>319765 AND t.kind_id>1;
SELECT COUNT(*) FROM movie_keyword mk,movie_info mi,movie_info_idx mi_idx,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=mi_idx.movie_id AND t.id=mi.movie_id AND t.id=mk.movie_id AND mk.keyword_id>13017 AND t.kind_id<7 AND mc.company_id=460;
SELECT COUNT(*) FROM movie_keyword mk,cast_info ci,movie_info_idx mi_idx,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.id=ci.movie_id AND t.id=mk.movie_id AND mi_idx.info_type_id>99 AND t.kind_id>1 AND t.production_year>2006;
SELECT COUNT(*) FROM cast_info ci,movie_companies mc,movie_keyword mk,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND t.id=mc.movie_id AND t.id=ci.movie_id AND ci.person_id=446805 AND ci.role_id>3 AND mk.keyword_id<2587;
SELECT COUNT(*) FROM movie_companies mc,movie_info mi,movie_info_idx mi_idx,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi_idx.movie_id AND t.id=mi.movie_id AND t.id=mc.movie_id AND mc.company_id>17397 AND mi.info_type_id<7 AND mi_idx.info_type_id>101 AND mk.keyword_id<365;
SELECT COUNT(*) FROM movie_info mi,movie_companies mc,cast_info ci,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=ci.movie_id AND t.id=mc.movie_id AND t.id=mi.movie_id AND mi.info_type_id=4 AND mc.company_id>28339 AND t.kind_id=7;
SELECT COUNT(*) FROM movie_info mi,cast_info ci,movie_keyword mk,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=mk.movie_id AND t.id=ci.movie_id AND t.id=mi.movie_id AND ci.person_id>201466 AND ci.role_id=2 AND mk.keyword_id<86290 AND t.kind_id=1 AND t.production_year>2010 AND mc.company_id<76379 AND mc.company_type_id>1;
SELECT COUNT(*) FROM movie_companies mc,movie_info_idx mi_idx,movie_info mi,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.id=mc.movie_id AND mi.info_type_id=16 AND t.kind_id<7 AND ci.person_id>440345;
SELECT COUNT(*) FROM movie_keyword mk,cast_info ci,movie_companies mc,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mc.movie_id AND t.id=ci.movie_id AND t.id=mk.movie_id AND ci.person_id<311385 AND mc.company_id<7975 AND mi_idx.info_type_id=101;
SELECT COUNT(*) FROM movie_info_idx mi_idx,cast_info ci,movie_companies mc,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mc.movie_id AND t.id=ci.movie_id AND t.id=mi_idx.movie_id AND mi_idx.info_type_id<100 AND mc.company_id>5026 AND t.kind_id=7 AND t.production_year>1964;
SELECT COUNT(*) FROM movie_companies mc,cast_info ci,movie_keyword mk,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND t.id=ci.movie_id AND t.id=mc.movie_id AND mk.keyword_id>3921 AND t.kind_id=1 AND t.production_year=2005 AND mi.info_type_id<7;
SELECT COUNT(*) FROM movie_info_idx mi_idx,movie_keyword mk,cast_info ci,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=ci.movie_id AND t.id=mk.movie_id AND t.id=mi_idx.movie_id AND mi_idx.info_type_id=100 AND mk.keyword_id>1514 AND ci.person_id=2965244 AND mi.info_type_id<15;
SELECT COUNT(*) FROM movie_info mi,movie_companies mc,cast_info ci,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=ci.movie_id AND t.id=mc.movie_id AND t.id=mi.movie_id AND mc.company_id<86468 AND mc.company_type_id=1 AND ci.person_id<2240313 AND ci.role_id=1 AND t.kind_id<7 AND mk.keyword_id>5120;
SELECT COUNT(*) FROM cast_info ci,movie_info_idx mi_idx,movie_info mi,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.id=ci.movie_id AND ci.person_id<1997287;
SELECT COUNT(*) FROM cast_info ci,movie_info_idx mi_idx,movie_companies mc,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mc.movie_id AND t.id=mi_idx.movie_id AND t.id=ci.movie_id AND mi_idx.info_type_id>99 AND mc.company_id=17380 AND mc.company_type_id>1 AND mk.keyword_id<7426;
SELECT COUNT(*) FROM cast_info ci,movie_keyword mk,movie_info mi,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND t.id=mk.movie_id AND t.id=ci.movie_id AND mc.company_id>92;
SELECT COUNT(*) FROM movie_info_idx mi_idx,movie_keyword mk,cast_info ci,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=ci.movie_id AND t.id=mk.movie_id AND t.id=mi_idx.movie_id AND mk.keyword_id<7771 AND ci.person_id=1166738;
SELECT COUNT(*) FROM movie_keyword mk,cast_info ci,movie_info_idx mi_idx,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=mi_idx.movie_id AND t.id=ci.movie_id AND t.id=mk.movie_id AND mk.keyword_id>19860 AND ci.person_id=3158882;
SELECT COUNT(*) FROM movie_companies mc,movie_info_idx mi_idx,movie_keyword mk,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND t.id=mi_idx.movie_id AND t.id=mc.movie_id AND t.kind_id<7 AND t.production_year=2004 AND mi.info_type_id<4;
SELECT COUNT(*) FROM movie_info_idx mi_idx,cast_info ci,movie_keyword mk,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=mk.movie_id AND t.id=ci.movie_id AND t.id=mi_idx.movie_id AND mi_idx.info_type_id<100 AND ci.person_id>3528859 AND t.kind_id>1 AND t.production_year=2007;
SELECT COUNT(*) FROM movie_keyword mk,movie_info_idx mi_idx,movie_companies mc,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mc.movie_id AND t.id=mi_idx.movie_id AND t.id=mk.movie_id AND mi_idx.info_type_id=101 AND ci.person_id>2171316 AND ci.role_id>1;
SELECT COUNT(*) FROM movie_keyword mk,movie_info_idx mi_idx,cast_info ci,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=ci.movie_id AND t.id=mi_idx.movie_id AND t.id=mk.movie_id AND mk.keyword_id>12114 AND ci.person_id=1341107;
SELECT COUNT(*) FROM movie_companies mc,movie_info_idx mi_idx,movie_keyword mk,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND t.id=mi_idx.movie_id AND t.id=mc.movie_id;
SELECT COUNT(*) FROM movie_info mi,movie_companies mc,movie_keyword mk,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND t.id=mc.movie_id AND t.id=mi.movie_id AND mi.info_type_id>16;
SELECT COUNT(*) FROM movie_keyword mk,movie_info_idx mi_idx,movie_companies mc,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mc.movie_id AND t.id=mi_idx.movie_id AND t.id=mk.movie_id AND mk.keyword_id>5043 AND mc.company_id>8112 AND t.kind_id<7 AND t.production_year<2006;
SELECT COUNT(*) FROM movie_keyword mk,movie_info_idx mi_idx,movie_info mi,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.id=mk.movie_id;
SELECT COUNT(*) FROM movie_info mi,movie_companies mc,movie_info_idx mi_idx,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mi_idx.movie_id AND t.id=mc.movie_id AND t.id=mi.movie_id AND mi.info_type_id<8 AND mi_idx.info_type_id=101 AND ci.person_id=2843975;
SELECT COUNT(*) FROM movie_info mi,movie_keyword mk,cast_info ci,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=ci.movie_id AND t.id=mk.movie_id AND t.id=mi.movie_id AND mi.info_type_id>3 AND t.kind_id=7 AND t.production_year=1977;
SELECT COUNT(*) FROM movie_info mi,movie_companies mc,movie_keyword mk,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND t.id=mc.movie_id AND t.id=mi.movie_id AND mc.company_id>11 AND mk.keyword_id<870 AND t.kind_id=7 AND ci.person_id=291966;
SELECT COUNT(*) FROM cast_info ci,movie_keyword mk,movie_info_idx mi_idx,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.id=mk.movie_id AND t.id=ci.movie_id AND ci.person_id<3453843 AND ci.role_id>9 AND mk.keyword_id<1074 AND mi_idx.info_type_id>99 AND t.kind_id<7 AND mi.info_type_id>7;
SELECT COUNT(*) FROM movie_info_idx mi_idx,movie_companies mc,movie_info mi,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mi.movie_id AND t.id=mc.movie_id AND t.id=mi_idx.movie_id AND mi_idx.info_type_id>100 AND mc.company_id>91513 AND t.kind_id<7;
SELECT COUNT(*) FROM cast_info ci,movie_info_idx mi_idx,movie_keyword mk,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=mk.movie_id AND t.id=mi_idx.movie_id AND t.id=ci.movie_id AND ci.person_id<1119376 AND mk.keyword_id<4346 AND t.kind_id<7 AND t.production_year<1996 AND mc.company_id<11118;
SELECT COUNT(*) FROM cast_info ci,movie_keyword mk,movie_info mi,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND t.id=mk.movie_id AND t.id=ci.movie_id AND mk.keyword_id<231;
SELECT COUNT(*) FROM movie_info_idx mi_idx,movie_companies mc,movie_info mi,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi.movie_id AND t.id=mc.movie_id AND t.id=mi_idx.movie_id AND mi.info_type_id=17;
SELECT COUNT(*) FROM cast_info ci,movie_keyword mk,movie_companies mc,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mc.movie_id AND t.id=mk.movie_id AND t.id=ci.movie_id AND mk.keyword_id<10110 AND t.kind_id<6 AND t.production_year<1991;
SELECT COUNT(*) FROM cast_info ci,movie_info mi,movie_companies mc,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mc.movie_id AND t.id=mi.movie_id AND t.id=ci.movie_id AND mi.info_type_id<3 AND mc.company_id<78291 AND mc.company_type_id>1 AND t.kind_id<7 AND t.production_year>2011 AND mk.keyword_id>2337;
SELECT COUNT(*) FROM movie_info mi,cast_info ci,movie_keyword mk,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND t.id=ci.movie_id AND t.id=mi.movie_id AND mk.keyword_id<25537 AND mi_idx.info_type_id>99;
SELECT COUNT(*) FROM movie_keyword mk,movie_info mi,movie_companies mc,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mc.movie_id AND t.id=mi.movie_id AND t.id=mk.movie_id AND mi.info_type_id<8 AND mc.company_id>11245 AND t.kind_id<7 AND t.production_year>1990 AND ci.person_id<3484131;
SELECT COUNT(*) FROM movie_info_idx mi_idx,movie_companies mc,movie_keyword mk,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND t.id=mc.movie_id AND t.id=mi_idx.movie_id AND mi_idx.info_type_id>99 AND mc.company_id=34511 AND mi.info_type_id>3;
SELECT COUNT(*) FROM movie_companies mc,movie_info mi,cast_info ci,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=ci.movie_id AND t.id=mi.movie_id AND t.id=mc.movie_id AND ci.person_id=3007394 AND t.kind_id=7 AND t.production_year<2010;
SELECT COUNT(*) FROM movie_info_idx mi_idx,movie_keyword mk,cast_info ci,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=ci.movie_id AND t.id=mk.movie_id AND t.id=mi_idx.movie_id AND t.kind_id=7 AND t.production_year>2007;
SELECT COUNT(*) FROM cast_info ci,movie_companies mc,movie_info_idx mi_idx,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi_idx.movie_id AND t.id=mc.movie_id AND t.id=ci.movie_id AND ci.person_id<2778058 AND t.kind_id<7 AND mk.keyword_id>107;
SELECT COUNT(*) FROM movie_companies mc,movie_info_idx mi_idx,movie_info mi,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.id=mc.movie_id AND mi.info_type_id>2;
SELECT COUNT(*) FROM movie_keyword mk,cast_info ci,movie_info_idx mi_idx,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.id=ci.movie_id AND t.id=mk.movie_id AND mi.info_type_id<2;
SELECT COUNT(*) FROM movie_info_idx mi_idx,movie_keyword mk,movie_companies mc,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mc.movie_id AND t.id=mk.movie_id AND t.id=mi_idx.movie_id AND mi_idx.info_type_id>101 AND mc.company_id>12501 AND t.kind_id<2 AND t.production_year<1992;
SELECT COUNT(*) FROM movie_keyword mk,movie_companies mc,cast_info ci,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=ci.movie_id AND t.id=mc.movie_id AND t.id=mk.movie_id AND ci.person_id>3413581 AND t.kind_id=1 AND t.production_year=1975 AND mi.info_type_id=17;
SELECT COUNT(*) FROM movie_companies mc,cast_info ci,movie_info mi,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi.movie_id AND t.id=ci.movie_id AND t.id=mc.movie_id AND mc.company_id>1880 AND mc.company_type_id=1;
SELECT COUNT(*) FROM movie_companies mc,movie_keyword mk,movie_info_idx mi_idx,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.id=mk.movie_id AND t.id=mc.movie_id AND mk.keyword_id<11604 AND t.kind_id=7 AND t.production_year=2004 AND mi.info_type_id=3;
SELECT COUNT(*) FROM cast_info ci,movie_companies mc,movie_info_idx mi_idx,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi_idx.movie_id AND t.id=mc.movie_id AND t.id=ci.movie_id AND mi_idx.info_type_id>99 AND mk.keyword_id<1322;
SELECT COUNT(*) FROM movie_companies mc,movie_keyword mk,cast_info ci,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=ci.movie_id AND t.id=mk.movie_id AND t.id=mc.movie_id AND ci.person_id<3670024;
SELECT COUNT(*) FROM movie_keyword mk,cast_info ci,movie_companies mc,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mc.movie_id AND t.id=ci.movie_id AND t.id=mk.movie_id AND mk.keyword_id>4458 AND ci.person_id>1038949 AND mc.company_id<11146 AND t.kind_id>1 AND t.production_year>1977 AND mi.info_type_id<98;
SELECT COUNT(*) FROM movie_companies mc,cast_info ci,movie_info_idx mi_idx,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.id=ci.movie_id AND t.id=mc.movie_id AND mi_idx.info_type_id=101;
SELECT COUNT(*) FROM movie_info mi,movie_keyword mk,cast_info ci,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=ci.movie_id AND t.id=mk.movie_id AND t.id=mi.movie_id AND mi.info_type_id<7 AND ci.person_id>2646763 AND ci.role_id<10;
SELECT COUNT(*) FROM movie_keyword mk,movie_info mi,movie_info_idx mi_idx,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mi_idx.movie_id AND t.id=mi.movie_id AND t.id=mk.movie_id AND mk.keyword_id=335 AND ci.person_id<2625958;
SELECT COUNT(*) FROM movie_companies mc,movie_info_idx mi_idx,movie_keyword mk,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND t.id=mi_idx.movie_id AND t.id=mc.movie_id AND mc.company_id<63481 AND mc.company_type_id>1 AND t.kind_id=7 AND t.production_year>2012 AND ci.person_id<2160080 AND ci.role_id>1;
SELECT COUNT(*) FROM movie_info_idx mi_idx,cast_info ci,movie_keyword mk,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND t.id=ci.movie_id AND t.id=mi_idx.movie_id AND mk.keyword_id>115 AND t.kind_id<7 AND mi.info_type_id<2;
SELECT COUNT(*) FROM movie_info mi,movie_companies mc,cast_info ci,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=ci.movie_id AND t.id=mc.movie_id AND t.id=mi.movie_id AND mi.info_type_id>2 AND mc.company_id>138341;
SELECT COUNT(*) FROM movie_keyword mk,movie_info_idx mi_idx,movie_info mi,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.id=mk.movie_id AND mi_idx.info_type_id>99 AND mc.company_id<32751;
SELECT COUNT(*) FROM movie_info_idx mi_idx,movie_companies mc,cast_info ci,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=ci.movie_id AND t.id=mc.movie_id AND t.id=mi_idx.movie_id AND mi_idx.info_type_id>99 AND t.kind_id>1 AND t.production_year<1977;
SELECT COUNT(*) FROM movie_companies mc,movie_info mi,movie_keyword mk,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND t.id=mi.movie_id AND t.id=mc.movie_id AND mc.company_id>46930 AND mc.company_type_id>1 AND mk.keyword_id=3402 AND t.kind_id<7 AND t.production_year>1960;
SELECT COUNT(*) FROM cast_info ci,movie_keyword mk,movie_info_idx mi_idx,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=mi_idx.movie_id AND t.id=mk.movie_id AND t.id=ci.movie_id AND t.kind_id=1 AND t.production_year>2009 AND mc.company_id<11872;
SELECT COUNT(*) FROM cast_info ci,movie_info mi,movie_keyword mk,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND t.id=mi.movie_id AND t.id=ci.movie_id AND t.kind_id=1 AND t.production_year<1989;
SELECT COUNT(*) FROM movie_companies mc,movie_info mi,movie_info_idx mi_idx,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi_idx.movie_id AND t.id=mi.movie_id AND t.id=mc.movie_id AND mc.company_id>1284 AND t.kind_id=7 AND mk.keyword_id>12857;
SELECT COUNT(*) FROM movie_info_idx mi_idx,movie_companies mc,cast_info ci,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=ci.movie_id AND t.id=mc.movie_id AND t.id=mi_idx.movie_id AND mi_idx.info_type_id>99 AND mc.company_id<4444 AND mc.company_type_id=2 AND ci.person_id>2236346 AND ci.role_id>1;
SELECT COUNT(*) FROM movie_keyword mk,movie_info_idx mi_idx,movie_companies mc,title t,cast_info ci WHERE t.id=ci.movie_id AND t.id=mc.movie_id AND t.id=mi_idx.movie_id AND t.id=mk.movie_id AND mk.keyword_id=2879 AND t.kind_id>2 AND t.production_year=2008 AND ci.person_id<3081122;
SELECT COUNT(*) FROM cast_info ci,movie_companies mc,movie_info_idx mi_idx,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi_idx.movie_id AND t.id=mc.movie_id AND t.id=ci.movie_id AND ci.person_id>1807118 AND t.kind_id>1 AND t.production_year>1955;
SELECT COUNT(*) FROM movie_info mi,cast_info ci,movie_info_idx mi_idx,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi_idx.movie_id AND t.id=ci.movie_id AND t.id=mi.movie_id AND ci.person_id>3030671 AND ci.role_id>1 AND t.kind_id=7 AND mk.keyword_id>4630;
SELECT COUNT(*) FROM movie_info mi,movie_companies mc,movie_info_idx mi_idx,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi_idx.movie_id AND t.id=mc.movie_id AND t.id=mi.movie_id AND t.kind_id>1 AND mk.keyword_id>1633;
SELECT COUNT(*) FROM cast_info ci,movie_keyword mk,movie_info mi,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND t.id=mk.movie_id AND t.id=ci.movie_id AND t.kind_id=1 AND mc.company_id>1746 AND mc.company_type_id=1;
SELECT COUNT(*) FROM cast_info ci,movie_info_idx mi_idx,movie_companies mc,title t,movie_info mi WHERE t.id=mi.movie_id AND t.id=mc.movie_id AND t.id=mi_idx.movie_id AND t.id=ci.movie_id AND ci.person_id>226461 AND mc.company_id=19 AND mc.company_type_id>1 AND t.kind_id<7;
SELECT COUNT(*) FROM movie_info mi,movie_companies mc,movie_info_idx mi_idx,title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.id=mi_idx.movie_id AND t.id=mc.movie_id AND t.id=mi.movie_id AND mi.info_type_id=90 AND mi_idx.info_type_id>100 AND mk.keyword_id=382;
SELECT COUNT(*) FROM movie_keyword mk,movie_companies mc,cast_info ci,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=ci.movie_id AND t.id=mc.movie_id AND t.id=mk.movie_id AND mc.company_id>319 AND ci.person_id<3433871 AND mi_idx.info_type_id=100;
SELECT COUNT(*) FROM movie_info mi,cast_info ci,movie_info_idx mi_idx,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=mi_idx.movie_id AND t.id=ci.movie_id AND t.id=mi.movie_id AND mi.info_type_id<16 AND mi_idx.info_type_id<101 AND t.kind_id>1 AND t.production_year>2008;
SELECT COUNT(*) FROM movie_keyword mk,movie_companies mc,movie_info mi,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mi.movie_id AND t.id=mc.movie_id AND t.id=mk.movie_id AND mc.company_id>3097 AND mc.company_type_id>1 AND mi.info_type_id>5;
SELECT COUNT(*) FROM movie_info_idx mi_idx,cast_info ci,movie_keyword mk,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=mk.movie_id AND t.id=ci.movie_id AND t.id=mi_idx.movie_id AND mi_idx.info_type_id>101 AND mk.keyword_id<84639 AND t.kind_id=1 AND mc.company_id>1475;
SELECT COUNT(*) FROM movie_info_idx mi_idx,movie_info mi,cast_info ci,title t,movie_companies mc WHERE t.id=mc.movie_id AND t.id=ci.movie_id AND t.id=mi.movie_id AND t.id=mi_idx.movie_id AND mi.info_type_id=18 AND t.kind_id<7 AND mc.company_id>1714;
SELECT COUNT(*) FROM cast_info ci,movie_companies mc,movie_info mi,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mi.movie_id AND t.id=mc.movie_id AND t.id=ci.movie_id AND ci.person_id>1272372 AND mc.company_id>12801 AND mc.company_type_id<2 AND t.kind_id<7 AND mi_idx.info_type_id>101;
SELECT COUNT(*) FROM movie_keyword mk,movie_companies mc,cast_info ci,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=ci.movie_id AND t.id=mc.movie_id AND t.id=mk.movie_id AND mk.keyword_id>10134 AND mc.company_id>513 AND mc.company_type_id>1;
SELECT COUNT(*) FROM cast_info ci,movie_info mi,movie_companies mc,title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.id=mc.movie_id AND t.id=mi.movie_id AND t.id=ci.movie_id;
